### PR TITLE
feat: add basic authentication in case user and password is provided in configuration, use url if provided in configuration

### PR DESCRIPTION
**Pull request by ktor**

### CODE REVIEW

**Comment by faragos** [comment]
Nice 👍  Didn't know somebody else uses it 😄 
Can you maybe also change the markdown? Then it's perfect.

You made my day 🥇

**Review by faragos — APPROVED** [review]

**Comment by ktor** [comment]
Hi @faragos, thank you for the library! I am no webpack expert so it helped a lot to have working webpack dev server proxy to liferay instance. It saved me a lot of time which I had donated to my 5 years old son, so he's indirectly thankful for you work as well :)

You may be interested how Liferay itself supports dev server/hotreload with their toolkit. I've tried the experimental dev server feature however haven't find a way of substituting runtime resolved npm (Liferay.Loader) modules with webpack generated ones with their experimental proxy: https://github.com/liferay/liferay-frontend-projects/pull/831

**Review by faragos — APPROVED** [review]

**Comment by faragos** [comment]
@ktor I'm glad I saved you some time. 😄 
Ye the Liferay stuff never worked for me so I wrote my own, because I want to see my portlet in the context it really is. Maybe the new one works better didn't tried it out. I will stop working with Liferay in 2-3 months so if you want access rights to this and the other repo you can have it 👍 

Also a friend of mine used my concept and wrote it from scratch. The premise sounds nice, but didn't have time to test it.
https://github.com/mauriceoegerli/viteray

**Comment by ktor** [comment]
hi @faragos, thank you, I will be using it for a longer time to come and I would love to be able to push the library further. What about publishing new version on npmjs? I presume `@cleavis` namespace is a company thing.

However I would consider focusing on viteray if it's a comparable thing. I am going to give it a try, thank you for the suggestion!

**Comment by faragos** [comment]
yes true I will need to check this 👍

**Pull request merged**
